---
title: "Tidy Tuesday Plastic Pollution"
author: "Anastasia Kunz"
date: "2/2/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(cartogram)
library(ggplot2)
library(broom)
library(tweenr)
library(gganimate)
library(maptools)
library(viridis)
library(leaflet)
library(maps)
library(sf)
library(janitor)
library(tigris)
library(here)

```

```{r}
plastics <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-01-26/plastics.csv')
```

ideas for tidy tuesday
cartogram https://www.r-graph-gallery.com/a-smooth-transition-between-chloropleth-and-cartogram.html  or
https://www.datanovia.com/en/lessons/highchart-interactive-world-map-in-r/


```{r}
long_plastic <- pivot_longer(plastics, c(hdpe, ldpe, o, pet, pp, ps, pvc), names_to = "plastic_type") %>% 
  filter(country != "EMPTY") %>% 
  mutate(country = tolower(country))

new_plastic <-plastics %>% 
  filter(country != "EMPTY") %>% 
  mutate(country = tolower(country))
```



## Wrangling:

```{r}
plastic_2019 <- new_plastic %>% 
  filter(year == 2019) %>% 
  filter(parent_company == "Grand Total")

```


```{r}
#data(wrld_simpl)
#plot(wrld_simpl)
```

### Exploring spatial



Try tmap???

```{r}
world_data <- read_sf(here("country-borders", "99bfd9e7-bb42-4728-87b5-07f8c8ac631c2020328-1-1vef4ev.lu5nk.shp")) %>% 
  clean_names() %>% 
  mutate(country_name = str_to_lower(cntry_name))
world_data %>% st_crs()

```

```{r}
joined_data <- geo_join(spatial_data = world_data, data_frame = plastic_2019, by_sp = "country_name", by_df = "country", by = NULL, how = "left")
```

```{r}
ggplot()+
  geom_sf(data = joined_data, aes(fill = grand_total))+
  scale_fill_gradientn(colors = c("yellow", "orange", "red"))+
  theme_void()+
  theme(panel.background = element_rect(fill = 'skyblue'))
```



